In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Question 1

In [2]:
# functions for problem 1
def buildHilbertMatrix(N):
    H  = np.zeros((N,N))
    for i in range(N):
        for j in range(N):
            H[i,j] = 1/( (i+1) + (j+1) -1 )
    return H

# calculate the condition number of a matrix
def conditionNumber(A):
    return np.linalg.cond(A)

In [3]:
N_list = [6, 10]
for N in N_list:
    H = buildHilbertMatrix(N)
    print("N = ", N)
    print("Hilbert Matrix")
    print(H)
    print("Condition number: ", conditionNumber(H))
    print("")

N =  6
Hilbert Matrix
[[1.         0.5        0.33333333 0.25       0.2        0.16666667]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]]
Condition number:  14951058.641453395

N =  10
Hilbert Matrix
[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 0.125      

## Question 2

Now let’s see how this condition number impacts the accuracy of solving a system of equations with the Hilbert matrix. Let’s set up a problem to solve where the exact solution is known and simple, namely where x is just an array of ones. We can then compute a right-hand side vector as b = Hx. Using b, calculate xa by using the solve function from the numpy.linalg module. Compare the approximate solution you get to the exact solution of ones for N = 6 and N = 10. Does the number of accurate digits in the solution change with the condition number you found in problem 2 as expected?

In [4]:
# lets try with N = 6
N = 6
H = buildHilbertMatrix(N)
x = np.ones(N)
b = H @ x

# now we use b to solve for x_a
x_a_N6 = np.linalg.solve(H, b)
print("x_a_N6 = ", x_a_N6)

N = 10
H = buildHilbertMatrix(N)
x = np.ones(N)
b = H @ x

# now we use b to solve for x_a
x_a_N10 = np.linalg.solve(H, b)
print("x_a_N10 = ", x_a_N10)

x_a_N6 =  [1. 1. 1. 1. 1. 1.]
x_a_N10 =  [1.         0.9999998  1.00000424 0.99996169 1.0001819  0.9995019
 1.00081456 0.99921504 1.00041109 0.99990979]


### Ans:
Yes, the matrix is unstable with small pertubation in the input argument. In this case, it can be seen that with N=10 (resp. a larget condition number) impacts the accuracy of solving the system of equations.

### Question 3

In [5]:
# find the infinity norm of the matrices ==> max row sum
A_1 = np.array([[1, 2],
              [3, 4]])

# infinity norm of A
print("Infinity norm of A_1: ", np.linalg.norm(A_1, np.inf))

A_2 = np.array([[1, 5, 1],
                [-1, 2, -3],
                [1, -7, 0]])

print("Infinity norm of A_2: ", np.linalg.norm(A_2, np.inf))

Infinity norm of A_1:  7.0
Infinity norm of A_2:  8.0


## Question 4

Find the forward and backward errors and error magnification factor for the given system.

Approx. solutions:
(a) [-1, 1]
(b) [3, -1]
(c) [2, -0.5]

In [6]:
# Given Ax = b, find x
A = np.array([[1, 2],
              [2, 4.01]])
b = np.array([1, 2])

# solve for x (the correct solution through direct solving)
x_corr = np.linalg.solve(A, b)
print("x_corr = ", x_corr)

x_corr =  [ 1. -0.]


In [7]:
## (a) x_a = [-1, 1]
x_a1 = np.array([-1, 1])
# find the residual vector, r = b - Ax_a
r = b - A @ x_a1
print("For (a) x_a1 = [-1, 1]")
# backward error 
back_err = np.linalg.norm(r, np.inf)
print("Backward error: ", back_err)
# forward error
for_err = np.linalg.norm(x_corr-x_a1, np.inf)
print("Forward error: ", for_err)
print("")


## (b) x_a = [3, -1]
x_a2 = np.array([3, -1])
# find the residual vector, r = b - Ax_a
r = b - A @ x_a2
print("For (b) x_a2 = [3, -1]")
# backward error
back_err = np.linalg.norm(r, np.inf)
print("Backward error: ", back_err)
# forward error
for_err = np.linalg.norm(x_corr-x_a2, np.inf)
print("Forward error: ", for_err)
print("")

## (c) x_a = [2, -0.5]
x_a3 = np.array([2, -0.5])
# find the residual vector, r = b - Ax_a
r = b - A @ x_a3
print("For (c) x_a3 = [2, -0.5]")
# backward error
back_err = np.linalg.norm(r, np.inf)
print("Backward error: ", back_err)
# forward error
for_err = np.linalg.norm(x_corr-x_a3, np.inf)
print("Forward error: ", for_err)

For (a) x_a1 = [-1, 1]
Backward error:  0.009999999999999787
Forward error:  2.0

For (b) x_a2 = [3, -1]
Backward error:  0.009999999999999787
Forward error:  2.0

For (c) x_a3 = [2, -0.5]
Backward error:  0.004999999999999893
Forward error:  1.0


## Question 5

Modify the func iterEqs to take an additional variable "A", which is the matrix of coefficients for the corresponding system of equations, as well as the right-side vector b. Modify the code in a generic  way such that it can generate the update equations based on the entires of A and b, regardless of the num of eq. (assuming is is square).

Test the code on the same 3x3 system we looked at in class for a single iteration, by calling the new function iterEqs once.

** Don't use the gaussSeidel.py module.

In [8]:
### original function

def iterEqs(x,omega): 
    x[0] = (1.0 - omega)*x[0] + omega*(4.0 - x[1] + x[2])/3.0
    x[1] = (1.0 - omega)*x[1] + omega*(1.0 - 2.0*x[0] - x[2])/4.0
    x[2] = (1.0 - omega)*x[2] + omega*(1.0 + x[0] - 2.0*x[1])/5.0
    return x

In [9]:
### updated function
def iterEqs_up(x, w, A, b):
    """
    x: initial guess
    w: relaxation factor in the SOR method
    A: matrix of coefficients ==> has to be a square
    b: right-side vector
    """
    # size of matrix, A
    N = A.shape[0]
    # overwrite x with each iteration
    x_up = x.copy().astype(float)

    # loop through each row
    for i in range(N):
        if (i != 0) and (i != N-1):
            x_up[i] = (1.0 - w)*x[i] + w* ( (b[i] + np.inner(A[i, :i], -1*x_up[:i]) + np.inner(A[i, i+1:], -1*x_up[i+1:])) ) / A[i, i]
        elif i == 0:
            x_up[i] = (1.0 - w)*x[i] + w* ( (b[i] + np.inner(A[i, 1:], -1*x_up[1:])) ) / A[i, i]
        elif i == N-1:
            x_up[i] = (1.0 - w)*x[i] + w* ( (b[i] + np.inner(A[i, :i], -1*x_up[:i])) ) / A[i, i]
    return x_up

# test system
A = np.array([[3, 1, -1],
              [2, 4, 1],
                [-1, 2, 5]])
b = np.array([4, 1, 1])
# initial guess
x0 = np.array([0, 0, 0])

print("For relaxation factor, w = 1.00")
# relaxation factor
w = 1.00
# number of iterations
iter1 = iterEqs_up(x0, w, A, b)
iter2 = iterEqs_up(iter1, w, A, b)
print("iter1 = ", iter1)
print("iter2 = ", iter2)
print("")

print("For relaxation factor, w = 1.25")
# relaxation factor
w = 1.25
# number of iterations
iter1 = iterEqs_up(x0, w, A, b)
iter2 = iterEqs_up(iter1, w, A, b)
print("iter1 = ", iter1)
print("iter2 = ", iter2)

For relaxation factor, w = 1.00
iter1 =  [ 1.33333333 -0.41666667  0.63333333]
iter2 =  [ 1.68333333 -0.75        0.83666667]

For relaxation factor, w = 1.25
iter1 =  [ 1.66666667 -0.72916667  1.03125   ]
iter2 =  [ 1.98350694 -1.0671658   1.02164714]
